"""report.py renders the fixture. Run: python3 -m pytest -q  OR  python3 backend/tests/test_report.py"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))

from report import render_report  # noqa: E402

FIXTURE = os.path.join(os.path.dirname(os.path.dirname(HERE)), "fixtures", "findings.json")
OUT = "/tmp/report.html"


def _fixture():
    with open(FIXTURE, encoding="utf-8") as fh:
        return json.load(fh)


def test_fixture_renders_every_finding():
    run = _fixture()
    html = render_report(run)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(html)
    for f in run["findings"]:
        assert f'id="{f["id"]}"' in html, f["id"]
        assert f["explanation"].split(";")[0][:40] in html or f["explanation"][:20] in html.replace("&quot;", '"').replace("&#x27;", "'")
    assert "Bilingual consistency sign-off" in html
    assert run["meta"]["en_title"] in html and run["meta"]["zh_title"] in html
    assert run["meta"]["company"] in html and run["meta"]["stock_code"] in html
    assert "English prevails" in html
    assert "Generated by Concord" in html
    assert "釋義補充" in html                      # unaligned section appendix
    assert "最後截止日期" in html                  # glossary table
    assert "@page" in html and "A4" in html
    assert "Reviewer</span><span>—" in html      # no reviewer on the fixture


def test_spans_are_marked():
    run = _fixture()
    html = render_report(run)
    assert "<mark>HK$12.4 million</mark>" in html
    assert "<mark>港幣1,210萬元</mark>" in html
    assert "<mark>31 December 2026</mark>" in html
    assert "<mark>may consider</mark>" in html
    # null spans render the passage untouched
    assert "The Target is principally engaged in the provision of freight forwarding" in html


def test_status_counts_and_escaping():
    run = _fixture()
    run["findings"][0]["status"] = "confirmed"
    run["findings"][1]["status"] = "dismissed"
    run["findings"][1]["dismiss_reason"] = "acceptable_variation"
    run["findings"][1]["note"] = "<script>alert(1)</script>"
    run["reviewer"] = "M. Durand"
    html = render_report(run)
    assert "Confirmed <b class=\"num\">1</b>" in html
    assert "Dismissed <b class=\"num\">1</b>" in html
    assert "Unreviewed <b class=\"num\">6</b>" in html
    assert "Acceptable variation" in html
    assert "<script>alert(1)</script>" not in html and "&lt;script&gt;" in html
    assert "M. Durand" in html


def test_empty_run():
    html = render_report({"run_id": "r_x", "meta": {}, "findings": [], "counts": {}})
    assert "No discrepancies were found" in html and "Generated by Concord" in html


if __name__ == "__main__":
    failed = 0
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            try:
                fn()
                print(f"ok    {name}")
            except Exception as e:  # noqa: BLE001
                failed += 1
                print(f"FAIL  {name}: {type(e).__name__}: {e}")
    print("all passed" if not failed else f"{failed} failed")
    sys.exit(1 if failed else 0)
